List<Map<String, dynamic>> issuesData = [
  {
    'id': '1',
    'title': 'Large pothole on Kenyatta Avenue',
    'description':
        'Deep pothole causing vehicle damage near the city center. Multiple cars have been affected.',
    'category': 'Roads',
    'location': 'Nairobi CBD',
    'timestamp': '2 hours ago',
    'status': 'pending',
    'imageUrl': '/placeholder.svg',
  },
  {
    'id': '2',
    'title': 'Streetlight not working on Moi Avenue',
    'description':
        'Streetlight has been out for over a week, causing safety concerns at night.',
    'category': 'Streetlights',
    'location': 'Nairobi CBD',
    'timestamp': '1 day ago',
    'status': 'in_progress',
    'imageUrl': '/placeholder.svg',
  },
  {
    'id': '3',
    'title': 'Garbage collection needed in Eastleigh',
    'description':
        'Overflowing garbage bins causing health hazards. Requesting urgent collection.',
    'category': 'Waste Management',
    'location': 'Eastleigh',
    'timestamp': '3 days ago',
    'status': 'resolved',
    'imageUrl': '/placeholder.svg',
  },
  {
    'id': '4',
    'title': 'Water leak in Westlands',
    'description':"Water leak from a burst pipe causing flooding in the area. Urgent repair needed.",
    'category': 'Water Supply',
    'location': 'Westlands',
    'timestamp': '5 days ago',
    'status': 'pending',
    'imageUrl': '/placeholder.svg',
  },
  {
    'id': '5',
    'title': 'Damaged sidewalk in Parklands',
    'description':
        'Sidewalk is cracked and uneven, posing a risk to pedestrians. Needs repair.',
    'category': 'Sidewalks',
    'location': 'Parklands',
    'timestamp': '1 week ago',
    'status': 'in_progress',
    'imageUrl': '/placeholder.svg',
  },
  {
    'id': '6',
    'title': 'Traffic light malfunction at Uhuru Highway',
    'description':
        'Traffic light is stuck on red, causing major traffic jams during peak hours.',
    'category': 'Traffic Management',
    'location': 'Uhuru Highway',
    'timestamp': '2 weeks ago',
    'status': 'resolved',
    'imageUrl': '/placeholder.svg',
  },
  {'id': '7',
    'title': 'Public toilet needs cleaning in Gikambura',
    'description':
        'Public toilet is dirty and needs urgent cleaning. Health hazard for users.',
    'category': 'Public Toilets',
    'location': 'Gikambura',
    'timestamp': '3 weeks ago',
    'status': 'pending',
    'imageUrl': '/placeholder.svg',
  },
  {'id': '8',
    'title': 'Damaged street sign in Karen',
    'description':
        'Street sign is bent and hard to read, causing confusion for drivers.',
    'category': 'Signage',
    'location': 'Karen',
    'timestamp': '1 month ago',
    'status': 'in_progress',
    'imageUrl': '/placeholder.svg',
  },
  {'id': '9',
    'title': 'Flooded road in Mombasa Road',
    'description':
        'Heavy rains have caused flooding on Mombasa Road, making it impassable for vehicles.',
    'category': 'Flooding',
    'location': 'Mombasa Road',
    'timestamp': '2 months ago',
    'status': 'resolved',
    'imageUrl': '/placeholder.svg',
  },
  {'id': '10',
    'title': 'Broken bench in Central Park',
    'description':
        'Public bench in Central Park is broken and needs repair. Unsafe for public use.',
    'category': 'Public Amenities',
    'location': 'Central Park',
    'timestamp': '3 months ago',
    'status': 'pending',
    'imageUrl': '/placeholder.svg',
  },
 
];
